version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/src
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - web
    db:
        image: postgres
        # ports:
        #     - "5432:5432"
    web:
        build: .
        # command: /bin/bash -c "sleep 7;python3 manage.py runserver 0.0.0.0:8000"
        command: /bin/bash -c "sleep 7;uwsgi uwsgi.ini"
        volumes:
            - .:/code
        ports:
            # - "8000:8000"
            - "9091:9091"
        depends_on:
            - db
        entrypoint: /code/entrypoint.sh
    # es:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    #     environment:
    #         - cluster.name=docker-cluster
    #         - bootstrap.memory_lock=true
    #         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #     ulimits:
    #         memlock:
    #             soft: -1
    #             hard: -1
    #         mem_limit: 1g
    #     volumes:
    #         - ./esdata:/usr/share/elasticsearch/data
    #     ports:
    #         - 9200:9200
