# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0009_merge_20170928_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tel',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='tel',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
