# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanage', '0003_auto_20170927_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('price', models.PositiveIntegerField()),
                ('detail', models.TextField(max_length=1023)),
                ('expire_date', models.TimeField()),
                ('is_period', models.BooleanField()),
                ('remaining_day', models.PositiveIntegerField(null=True)),
                ('is_limit', models.BooleanField()),
                ('remain', models.IntegerField(null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storemanage.Currency')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.Store')),
            ],
        ),
    ]
