# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storemanage', '0002_auto_20170927_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='expire_date',
        ),
    ]
