# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 14:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storemanage', '0008_auto_20170930_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='raw_stat',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='currency',
            name='stat',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='ticket',
            name='raw_stat',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='ticket',
            name='stat',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
