# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storemanage', '0007_merge_20170930_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='attribute',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attribute',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
