# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('customer_rigths', 'Global customer rights'), ('store_rights', 'Global store rights'), ('any_rights', 'Global any rights')),
                'managed': False,
            },
        ),
    ]
