# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_auto_20170927_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
