# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0005_auto_20170928_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'managed': False, 'permissions': (('customer_rights', 'customer_rights'), ('store_rights', 'store_rights'))},
        ),
    ]
