# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0004_customer_birthdate'),
        ('usermanage', '0006_auto_20170928_1104'),
    ]

    operations = [
    ]
