# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0008_merge_20170928_1431'),
        ('usermanage', '0008_merge_20170928_1442'),
    ]

    operations = [
    ]
