# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storemanage', '0003_remove_ticket_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='expire_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
