# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storemanage', '0005_auto_20170928_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
