# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0004_auto_20170928_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'managed': False, 'permissions': (('customer_rights', 'customer rights'), ('store_rights', 'store rights'))},
        ),
    ]
