# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0010_auto_20170929_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
