# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0011_auto_20170930_0025'),
        ('usermanage', '0011_auto_20170930_0015'),
    ]

    operations = [
    ]
