# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0013_auto_20170930_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='thumbnail_image_url',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='thumbnail_image_url',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
