# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0014_auto_20170930_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='thumbnail_image_url',
            new_name='profile_image_url',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='thumbnail_image_url',
            new_name='profile_image_url',
        ),
    ]
