# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customermanage', '0002_auto_20170930_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='attribute',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='attribute',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
